on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * 0 0"

name: check-and-build

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@master
        with: 
          r-version: '3.6.3'
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.9.2' 
      - run: echo "# Test" | pandoc -t html
      - name: Setup TinyTex 
        uses: r-lib/actions/setup-tinytex@v1
      - run: tlmgr --version
      - name: Install dependencies
        run: sudo apt-get install libcurl4-openssl-dev
      - name: Install R dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
      - name: Build
        run: rmarkdown::render("cv/cv.Rmd")
        shell: Rscript {0}
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        id: create_release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Development Build
          files: cv/cv.pdf
